
-- Modificar abstraccio     (Fet)
-- Afegir operacions        (Fet)
-- Main                     (Fet)
    -- Dir si passa o no
        -- Si no:
            -- Missatges d'on està el fallo
        -- Si sí:
            -- Imprimir l'arbre 
-- Preparar els tipus (Dimecres 18 de Març)                                   (Fet)
-- Guardar tipus de funcions predefinides (Dijous 19 de Març)                 (Fet)
-- Enviar correu per ajendar reunió presencial (intentar Setmana 23 de Març)  (Fet)
-- Reunió                                                                     (Fet)
-- Inferencia tipus                                                           (Fet)
-- Reunió 2                                                                   (Fet)
-- Eval lazy
-- Super combinadors
-- Guardes / if-else
-- Let
-- Composició
-- Constructors
-- Patrons
-- Memòria

-- Dilluns matí fins 13 i dijous 10-16
