
-- Modificar abstraccio     (Fet)
-- Afegir operacions        (Fet)
-- Main                     (Fet)
    -- Dir si passa o no
        -- Si no:
            -- Missatges d'on està el fallo
        -- Si sí:
            -- Imprimir l'arbre 
-- Preparar els tipus (Dimecres 18 de Març)
-- Guardar tipus de funcions predefinides (Dijous 19 de Març)
-- Enviar correu per ajendar reunió presencial (intentar Setmana 23 de Març)
-- Reunió
-- Inferencia tipus
-- Reunió 2
-- Eval lazy<
-- Super combinadors
-- Guardes
-- Composició
-- Constructors
-- Patrons

-- Dilluns matí fins 13 i dijous 10-16
